# Generated by Django 4.0.2 on 2022-02-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.TextField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orm.role')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_email', models.CharField(max_length=50)),
                ('employee_password', models.CharField(max_length=50)),
                ('employee_phone', models.CharField(max_length=50)),
                ('employee_address', models.TextField()),
                ('employee_dob', models.DateField()),
            ],
            options={
                'db_table': 'employee',
            },
            bases=('orm.role',),
        ),
    ]
