# Generated by Django 4.0.2 on 2022-03-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='city',
            table='city123',
        ),
    ]
